service: serverless-bolt-js
frameworkVersion: '3'
provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs18.x
  deploymentMethod: direct
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline

  - serverless-dotenv-plugin

useDotenv: true
custom:
  serverless-offline:
    noPrependStageInUrl: true
  dotenv:
    exclude:
      - GITHUB_TOKEN
